Ecomex/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import include

from account.views import (
    register_view, login_view, logout_view, manage_view
)
from EcomexApp.views import (
    index, error404,
)

urlpatterns = [
	path('admin/', admin.site.urls),
    path('register/', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('manage/', manage_view, name="manage"),

    path('', index, name="index"),
    path('error404/', error404, name="error404"),

    #snippets
    path('products/', include('product.urls', namespace='product')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('revenue/', include('revenue.urls', namespace='revenue')),

] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

product/urls.py
from django.urls import path

from product.views import (
    product_items, add_product, upload_product, dropzone_image, option_select, edit_product,
    collections, add_collection, upload_collection, upload_thumbnail_collection, collection_details
)

app_name = 'product'

urlpatterns = [
    #product

	path('', product_items, name="product_items"),
	path('add_product/', add_product, name="add_product"),
	path('upload_product/', upload_product, name="upload_product"),
    path('edit_product/<str:pro_id>', edit_product, name="edit_product"),
    path('items/', product_items, name="product_items"),

    path('dropzone_image/', dropzone_image, name="dropzone_image"),
    path('option_select/', option_select, name="option_select"),

    #collections
    path('collections/', collections, name="collections"),
	path('add_collection/', add_collection, name="add_collection"),
    path('upload_collection/', upload_collection, name="upload_collection"),
    path('upload_thumbnail_collection/', upload_thumbnail_collection, name="upload_thumbnail_collection"),
    path('collections/<str:coll_id>', collection_details, name="collection_details"),

]

shop/urls.py
from django.urls import path

from shop.views import (
    shop_view, detail, add_order, my_cart, update_cart, checkout,
    send_order
    )

app_name = 'shop'

urlpatterns = [
    #shop
	path('', shop_view, name="shop_view"),
	path('detail/<str:pro_id>', detail, name="detail"),
	path('add_order', add_order, name="add_order"),
	path('my_cart', my_cart, name="my_cart"),
	path('update_cart', update_cart, name="update_cart"),
    path('checkout', checkout, name="checkout"),
    path('send_order', send_order, name="send_order"),
]

product/models.py
from datetime import date
today = date.today()

from django.db import models

# Create your models here.

def get_collection_image_filepath(self, filename):
    return 'collections/' + '/collection_image'+ str(self.pk) +'.png'

def default_thumb_path():
    return 'default/'+'thumb_default.png'

class Collections(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=225)
    Thumbnail = models.ImageField(upload_to=get_collection_image_filepath, default=default_thumb_path)
    description = models.TextField(default="No description for this Collection!")
    start_date = models.CharField(default=today.strftime("%B %d, %Y"), max_length=255)
    objects = models.Manager()

    def __str__(self):
        return self.name

class Products(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    detail = models.TextField(max_length=225)
    price = models.FloatField()
    brand = models.CharField(max_length=200)
    collection = models.IntegerField(default=0)
    rate = models.IntegerField(max_length=6, default=0)
    Availability = models.BooleanField(default=True)
    Description = models.TextField(default='No Description for this Items')
    objects = models.Manager()


class Genre(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=225)
    gender = models.CharField(max_length=225)
    products = models.ManyToManyField(Products)
    objects = models.Manager()


class Product_color(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    objects = models.Manager()

    def __str__(self):
        return self.name

class Product_size(models.Model):
    id = models.AutoField(primary_key=True)
    name_size = models.CharField(max_length=200)

    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    objects = models.Manager()

    def __str__(self):
        return self.name_size


def get_product_image_filepath(self, filename):
    return 'products/' + '/profile_image'+ str(self.pk) +'.png'

def get_default_product_image():
    return "default/default_product.png"

class Product_image(models.Model):
    id = models.AutoField(primary_key=True)
    key = models.BooleanField(default=False)
    product_image = models.ImageField(upload_to=get_product_image_filepath)
    product_id = models.ForeignKey(Products, on_delete=models.CASCADE)
    objects = models.Manager()

    def get_profile_image_filename(self):
        return str(self.product_image)
        # return str(self.product_image)[str(self.product_image).index(str(self.pk) + "/"):]

product/views.py
import json


from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from product.models import Products, Product_image, Product_color, Product_size, Collections

from django.template.defaulttags import register


@register.filter(name='get_item')
def get_item(dictionary, key):
    return dictionary.get(key)


def vertify_staff(request):
    user = request.user
    if user.is_authenticated and user.is_staff == True:
        return "ok"
    else:
        return "error"


    # Collections
def collections(request):
    cart_cnt = 0
    if vertify_staff(request) == "ok":
        status = "products"
    else:
        status = "collection"
    coll_cnt = Collections.objects.all().count()
    colls = []
    if coll_cnt != 0:
        colls = Collections.objects.all().order_by('-id')

    return render(request, "staffs/collections.html", {'status': status, 'coll_cnt': coll_cnt, 'colls': colls, 'cart_cnt': cart_cnt})

def collection_details(request, coll_id):
    status = "products"
    if vertify_staff(request) == "error":
        return redirect("error404")

    coll = Collections.objects.get(id=coll_id)
    product_list = Products.objects.filter(collection=coll_id)
    return render(request, "staffs/collection_detail.html", {'status': status, 'coll': coll, 'product_list':product_list})


def add_collection(request):
    status = "products"
    if vertify_staff(request) == "error":
        return redirect("error404")

    return render(request, "staffs/add_collection.html",{"status": status})

def upload_collection(request):
    if vertify_staff(request) == "error":
        return redirect("error404")

    status = "products"
    if request.method == "POST":

        title = request.POST.get('title')
        description = request.POST.get('description')
        print(title)
        print(description)
        try:
            coll = Collections(name=title)
            coll.save()
            print("oke")
            if description != "":
                coll.description = description
            coll.save()
            print("success coll")
            ID = coll.id
            print(ID)
            result = "perfect"
            message = "Your profile has been updated"

            context = {"result": result, "message": message, "ID": ID, }
            return HttpResponse(
                json.dumps(context),
                content_type="application/json"
            )
        except:
            result = "failed"
            message = "the process is failed!"
            ID = "0"
            context = {"result": result, "message": message, "ID": ID, }

            return HttpResponse(
                json.dumps(context),
                content_type="application/json"
            )
    return redirect("collections")

def upload_thumbnail_collection(request):
    if vertify_staff(request) == "error":
        return redirect("error404")

    result = "result"
    message = "message"
    if request.method == "POST":
        id = request.POST.get('pid')
        coll = Collections.objects.get(id=id)
        try:
            thumb_img = ""
            print(request.FILES)
            for image in request.FILES:
                thumb_img = request.FILES[image]

            if thumb_img != "":
                coll.Thumbnail = thumb_img
                coll.save()
                print("success thumb")
            return HttpResponse({}, content_type="application/json")
        except:
            return HttpResponse('failed')


    # products
def product_items(request):
    status = "products"
    user = request.user
    if user.is_authenticated and user.is_staff == True:
        products = []
        colors = {}
        sizes = {}
        images = {}
        if (Products.objects.all().count() != 0):
            products = Products.objects.all()
            for product in products:
                colors[product] = Product_color.objects.filter(product_id=product)
                sizes[product] = Product_size.objects.filter(product_id=product)
                for i in Product_image.objects.filter(product_id=product):
                    print(i.key)
                print(Product_image.objects.filter(product_id=product).count())
                image = Product_image.objects.get(product_id=product, key=True)

                images[product] = image.product_image.url
        print(products, colors, sizes)
        return render(request, 'staffs/product_items.html',
                      {'status': status, 'products': products, 'colors': colors, 'sizes': sizes, 'images': images})
    else:
        return redirect("error404")


def add_product(request):
    status = "products"
    if vertify_staff(request) == "error":
        return redirect("error404")

    colls = []
    if (Collections.objects.all().count() != 0):
        colls = Collections.objects.all()
    return render(request, 'staffs/add.html', {'status': status, 'colls': colls})

def edit_product(request, pro_id):
    status = "products"
    if vertify_staff(request) == "error":
        return redirect("error404")

    product = Products.objects.get(id = pro_id)
    collection = Collections.objects.get(id = product.collection)
    coll_id = collection.id
    coll_name = collection.name
    colls = Collections.objects.all()
    images = Product_image.objects.filter(product_id = product)
    return render(request, "staffs/edit_items.html", {'status': status, 'product': product, 'images': images,
                                                      'coll_id': coll_id, 'coll_name': coll_name,'colls': colls})

def upload_product(request):
    status = "products"
    if request.method == "POST":

        title = request.POST.get('title')
        category = request.POST.get('category')
        gender = request.POST.get('gender')
        collection = request.POST.get('collection')
        brand = request.POST.get('brand')
        detail = request.POST.get('detail')
        description = request.POST.get('description')
        price = request.POST.get('prices')

        try:
            product = Products(name=title, detail=detail, price=price, Description=description, collection=collection, brand=brand)
            product.save()

            ID = product.id
            result = "perfect"
            message = "Your profile has been updated"

            context = {"result": result, "message": message, "ID": ID, }
            return HttpResponse(
                json.dumps(context),
                content_type="application/json"
            )
        except:
            result = "failed"
            message = "the process is failed!"
            ID = "0"
            context = {"result": result, "message": message, "ID": ID, }

            return HttpResponse(
                json.dumps(context),
                content_type="application/json"
            )
    return render(request, 'staffs/add.html', {'status': status})

def dropzone_image(request):
    result = "result"
    message = "message"
    if request.method == "POST":
        id = request.POST.get('pid')
        product = Products.objects.get(id=id)
        try:
            print(request.FILES)

            for image in request.FILES:
                product_img = Product_image(product_image=request.FILES[image], product_id=product)
                print(product_img.key)
                product_img.save()

            for p in Product_image.objects.filter(product_id=product):
                p.key = True
                p.save()
                break

            return HttpResponse({}, content_type="application/json")
        except:
            return HttpResponse('failed')

    return HttpResponse(
        json.dumps({"result": result, "message": message}),
        content_type="application/json"
    )


def option_select(request):
    result = "result"
    message = "message"

    if request.POST:
        id = request.POST.get('pid')
        unit = request.POST.get('unit')

        colors = request.POST.getlist('colors[]')
        sizes = request.POST.getlist('sizes[]')
        size_shoes = request.POST.getlist('size_shoes[]')

        print(colors)
        print(size_shoes)
        print(sizes)
        print(id)
        product = Products.objects.get(id=id)
        try:
            print("vao")
            if colors != []:
                print("vao colors")
                for color in colors:
                    print(color)
                    print(product)
                    Product_color.objects.create(name=color, product_id=product)
                    print("save")
            print("success color")
            if size_shoes != []:
                print("vao size shoes")
                for size in size_shoes:
                    product_size = Product_size(name=str(size + unit), product_id=product)
                    product_size.save()
            elif sizes != []:
                print("vao size")
                for size in sizes:
                    product_size = Product_size(name_size=size, product_id=product)
                    product_size.save()
            print("success size")
        except:
            return HttpResponse('failed1')

        return redirect("product:add_product")

    return HttpResponse(
        json.dumps({"result": result, "message": message}),
        content_type="application/json"
    )

product/templates/staffs/add_collection.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
<link rel="stylesheet" href="{% static 'Ecomex2/css/dropzone/dropzone.css'%}" type="text/css">

{% endblock css %}
{% block content %}
    <section class="bg-light mt-5">
        <div class="container">
            <div class="row">
                <div class="card" style=" box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);  border-radius: 25px; background-size: cover;  width:1170px;">
                    <div class="card-body">
                        <div class="section-title" style=" text-align: center;"><h4>Add Collection</h4></div>
<!--                        <form action="{% url 'product:upload_product' %}" enctype="multipart/form-data" method="POST">-->
<!--                            {% csrf_token %}-->
                            <div class="row" style="padding: 30px;">
                                <div class="col-lg-3">
                                    <div class="row no-gutters"  style="align-items: center; justify-content: center;">
                                        <div class="col-12" style="text-align: center;">
                                            <div class="add_products">
                                                <div class="section-title">
                                                    <h4>Upload Thumbnail</h4>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="w-100"></div>
                                        <div class="col-7">
                                            <form class="dropzone dropzone-custom needsclick" style="padding: 10px; width: 156px;"  action="{% url 'product:upload_thumbnail_collection' %}"  id="DidDropzone" method="POST">
                                                <div class="dz-message needsclick download-custom">
                                                    {% csrf_token %}
                                                    <input type="text" hidden name="pid" id="productID">
                                                    <i class="fa fa-cloud-download" aria-hidden="true"></i>
                                                    <h6>Thumbnail</h6>
                                                </div>
                                            </form>
                                            <button disabled hidden id="image-btn" type="submit" >Add images</button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-9">
                                    <div class="add_products">
                                        <div class="section-title" style="text-align: center;">
                                            <h4>New Collection Information</h4>
                                        </div>
                                    </div>
                                    <form id="commentform" method="POST"  action="{% url 'product:upload_collection' %}">
                                        {% csrf_token %}
                                    <div class="form-group">
                                        <label class="label_form_title" for="title_product" style="float: left;">Title Product</label>
                                        <input type="text" class="form-control" name="title" id="title_product" placeholder="ESSENTIAL STRUCTURED BLAZER" required>
                                    </div>
                                    <div class="form-group">
                                        <label class="label_form_title" for="description" style="float: left;">Description</label>
                                        <textarea  class="form-control" rows=4" name="description" id="description" placeholder="Description"></textarea>
                                    </div>
                                        <button type="submit" class="btn-save" style="vertical-align:middle; float:right;"><span>Save</span></button>
                                    </form>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

{% block js %}
    <script src="{% static 'Ecomex2/js/dropzone/dropzone.js' %}"></script>
    <script src="{% static 'Ecomex1/js/mydropzone.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>

<script>

    var temp_button_text;

function CustomFormSubmitPost(e){
    var el = $(e);
    temp_button_text = el.text()
    el.attr('disabled', 'disabled').text("").append('<class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>Loading...');
};

function CustomFormSubmitResponse(e){
    var el = $(e);
    el.removeAttr('disabled').text(temp_button_text);
};
        var form = $('#commentform');
        form.submit(function(event){
            event.preventDefault();
            CustomFormSubmitPost($('#commentform button[type=submit]'));

            var formdata = form.serialize()
            $.ajax({
                url: form.attr("action"),
                method: form.attr("method"),
                data: formdata,

                 success: function(json){
                    CustomFormSubmitResponse($('#commentform button[type=submit]'));
                    document.getElementById("productID").value = json["ID"];
                    $('#image-btn').removeAttr("disabled").click()
                    alert('success')
                },
                error: function(xhr){
                    alert("failed");
                }
            })

        })

</script>

{% endblock js %}

product/templates/staffs/collection_detail.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
{% endblock css %}

{% block content %}
<section class="section_bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-12" style="text-align: center;">
                    <div class="collections" >
                        <div class="section-title">
                            <h4>Collections</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>


{% endblock content %}

{% block js %}
{% endblock js %}

product/templates/staffs/collections.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
{% endblock css %}

{% block content %}
<section class="bg-light mt-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-12" style="text-align: center;">
                    <div class="collections" >
                            <div class="section-title">
                                <h4>Collections</h4>
                            </div>
                    </div>
                </div>
                    {% if coll_cnt == 0 %}
                    <div class="row">
                        {% if request.user.is_staff == True %}
                        <div class="col-lg-10">
                            <h6 class="coupon__link" style="border-radius:5px;"><span><i class="fa fa-bullhorn" aria-hidden="true"></i></span> There is not any collection now! </h6>
                        </div>
                        <div class="col-lg-2">
                             <a href="{% url 'product:add_collection' %}">
                                <button class="btn-add" style="float: right;">
                                    <span><i class="fa fa-plus"></i></span> COLLECTION
                                </button>
                             </a>
                        </div>
                    </div>
                    {% else %}
                <div class="col-lg-12">
                            <h6 class="coupon__link" style="border-radius:5px;"><span><i class="fa fa-bullhorn" aria-hidden="true"></i></span> There is not any collection now! </h6>
                        </div>
                    {% endif %}
                    {% else %}
                    <div class="row" style >
                        {% if request.user.is_staff == True %}
                        <div class="col-10" style="border-radius:5px; float: center;">
                            <h6 class="coupon__link"><span><i class="fa fa-bullhorn" aria-hidden="true"></i></span> You have {{coll_cnt}} collections here! </h6>
                        </div>
                        <div class="col-2" style="position: absolute;  right:50px">
                             <a href="{% url 'product:add_collection' %}">
                                <button class="btn-add">
                                    <span><i class="fa fa-plus"></i></span> COLLECTION
                                </button>
                             </a>
                        </div>
                        {% else %}
                        <div class="col-12" style="border-radius:5px; float: center;">
                            <h6 class="coupon__link"><span><i class="fa fa-bullhorn" aria-hidden="true"></i></span> You have {{coll_cnt}} collections here! </h6>
                        </div>
                        {% endif %}
                        {% for coll in colls %}
                        <div class="col-lg-4 col-md-4 col-sm-6">
                            <div class="blog__item">
                                <div class="blog__item__pic set-bg" style="border-radius:10px;" data-setbg="{{coll.Thumbnail.url}}"></div>
                                <div class="blog__item__text" style="border-radius:10px; padding:20px;">
                                    <h6><a href="{% url 'product:collection_details' coll.id  %}">{{coll.name}}</a></h6>
                                    <ul>
                                        <li>by <span>Ecomex Team</span></li>
                                        <li>{{coll.start_date}}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>


                    {% endif %}

            </div>
        </div>
</section>


{% endblock content %}

{% block js %}
{% endblock js %}

product/templates/staffs/product_items.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
  <link href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.8/semantic.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/1.12.1/css/dataTables.semanticui.min.css" rel="stylesheet">
  <link href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.semanticui.min.css" rel="stylesheet">
<style>
table,
thead,
tr,
tbody,
th,
td {
  text-align: center;
}

.table {
table-layout: auto;
  width: 100%;
  }
.table td {
    font-size: 16px;
  text-align: center;
}
</style>
{% endblock css %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <section class="contact spad">
                <div class="container">
                    <div class="row">
                        <div class="justify-content-center">
                           <div class="card" style=" box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);  border-radius: 25px; text-align: center; background-size: hover; width: 1180px;">
                               <div class="card-body">
                                   <div class="section-title"><h4>All Items</h4></div>

                                   <table id="example" class="ui celled table" style=" margin-left: 15px; margin-right: 15px;">
                                       <thead>
                                            <tr>
                                                 <th>Name of Product</th>
                                                <th>Thumbnail</th>
                                                <th>Price</th>
                                                <th>Brand</th>
                                                <th>Color Options</th>
                                                <th>Size Options</th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for product in products %}
                                            <tr>
                                                <td><a href="{% url 'product:edit_product' product.id %}">{{product.name}}</a></td>
                                                <td>
                                                    <a href="{{images|get_item:product}}"  target=”_blank”>
                                                        <img class="img_thumbnail" src=" {{images|get_item:product}}">
                                                    </a>
                                                </td>
                                                <td>${{product.price}}</td>
                                                <td>{{product.brand}}</td>
                                                <td>
                                                    {% for color in colors|get_item:product %}

                                                    <span class="badge badge-primary custom_badge_color {{color.name}}">{{color.name}}</span>
                                                    {% endfor %}
                                                </td>
                                                <td>
                                                    {% for size in sizes|get_item:product %}
                                                    <span class="badge badge-primary custom_badge_size">{{size.name_size}}</span>
                                                    {% endfor %}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>Name</th>
                                                <th>Thumbnail</th>
                                                <th>Price</th>
                                                <th>Brand</th>
                                                <th>Color Options</th>
                                                <th>Size Option</th>

                                            </tr>
                                        </tfoot>
                                    </table>
                               </div>
                           </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>


{% endblock content %}

{%block js %}
 <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.8/semantic.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.12.1/js/dataTables.semanticui.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.semanticui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.colVis.min.js"></script>
<script>
$.fn.dataTable.ext.buttons.add = {
    text: 'Add Products',
    action: function ( e, dt, node, config ) {
       window.location.href = '/products/add_product'
    }
};
    $(document).ready(function() {
    var table = $('#example').DataTable( {
        lengthChange: false,
        buttons: [ 'copy', 'excel', 'pdf', 'colvis', 'add' ]
    } );

    table.buttons().container()
        .appendTo( $('div.eight.column:eq(0)', table.table().container()) );
} );
</script>
{%endblock js%}