Ecomex/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import include

from account.views import (
    register_view, login_view, logout_view, manage_view
)
from EcomexApp.views import (
    index, error404,
)

urlpatterns = [
	path('admin/', admin.site.urls),
    path('register/', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('manage/', manage_view, name="manage"),

    path('', index, name="index"),
    path('error404/', error404, name="error404"),

    #snippets
    path('products/', include('product.urls', namespace='product')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('revenue/', include('revenue.urls', namespace='revenue')),

] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from orders.views import (
orders_view, order_processing
   )

app_name = 'orders'

urlpatterns = [
    #product
    path('', orders_view, name="orders_view"),
    path('order_processing/', order_processing, name="order_processing"),
]

product/urls.py
from django.urls import path

from product.views import (
    product_items, add_product, upload_product, dropzone_image, option_select, edit_product,
    collections, add_collection, upload_collection, upload_thumbnail_collection, collection_details
)

app_name = 'product'

urlpatterns = [
    #product

	path('', product_items, name="product_items"),
	path('add_product/', add_product, name="add_product"),
	path('upload_product/', upload_product, name="upload_product"),
    path('edit_product/<str:pro_id>', edit_product, name="edit_product"),
    path('items/', product_items, name="product_items"),

    path('dropzone_image/', dropzone_image, name="dropzone_image"),
    path('option_select/', option_select, name="option_select"),

    #collections
    path('collections/', collections, name="collections"),
	path('add_collection/', add_collection, name="add_collection"),
    path('upload_collection/', upload_collection, name="upload_collection"),
    path('upload_thumbnail_collection/', upload_thumbnail_collection, name="upload_thumbnail_collection"),
    path('collections/<str:coll_id>', collection_details, name="collection_details"),

]

revenue/urls.py
from django.urls import path

from revenue.views import (
   revenue_view,
   )

app_name = 'revenue'

urlpatterns = [
    #revenue

	path('', revenue_view, name="revenue_view"),


]

shop/urls.py
from django.urls import path

from shop.views import (
    shop_view, detail, add_order, my_cart, update_cart, checkout,
    send_order
    )

app_name = 'shop'

urlpatterns = [
    #shop
	path('', shop_view, name="shop_view"),
	path('detail/<str:pro_id>', detail, name="detail"),
	path('add_order', add_order, name="add_order"),
	path('my_cart', my_cart, name="my_cart"),
	path('update_cart', update_cart, name="update_cart"),
    path('checkout', checkout, name="checkout"),
    path('send_order', send_order, name="send_order"),
]

templates/snippets/footer.html
{% load static %}

<!-- Footer Section Begin -->
<footer class="footer" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-7">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="./index.html"><img src="{% static 'Ecomex1/img/logo.jpg'%}" style='width: 150px; height: 100%; margin-bottom: -20px; margin-top: -15px;' alt=""></a>
                    </div>
                    <p>Local Brand from Vietnam - Leading for Future Fashion Trending.</p>
                    <div class="footer__payment">
                        <a href="#"><img src="{% static 'Ecomex1/img/payment/payment-1.png'%}" alt=""></a>
                        <a href="#"><img src="{% static 'Ecomex1/img/payment/payment-2.png'%}" alt=""></a>
                        <a href="#"><img src="{% static 'Ecomex1/img/payment/payment-3.png'%}" alt=""></a>
                        <a href="#"><img src="{% static 'Ecomex1/img/payment/payment-4.png'%}" alt=""></a>
                        <a href="#"><img src="{% static 'Ecomex1/img/payment/payment-5.png'%}" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-3 col-sm-5">
                <div class="footer__widget">
                    <h6>Quick links</h6>
                    <ul>
                        <li><a href="{% url 'shop:shop_view' %}">Shop</a></li>
                        <li><a href="{% url 'product:collections' %}">Collection</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">FAQ</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-8 col-sm-8">
                <div class="footer__newslatter">
                    <h6>NEWSLETTER</h6>
                    <form action="#">
                        <input type="text" placeholder="Email">
                        <button type="submit" class="site-btn">Subscribe</button>
                    </form>
                    <div class="footer__social">
                        <a href="https://www.facebook.com/ceonhy.np"><i class="fa fa-facebook"></i></a>
                        <a href="https://twitter.com/AvieTechy"><i class="fa fa-twitter"></i></a>
                        <a href="https://www.linkedin.com/in/avietechy/"><i class="fa fa-linkedin"></i></a>
                        <a href="https://github.com/AvieTechy"><i class="fa fa-github"></i></a>
                        <a href="#"><i class="fa fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                <div class="footer__copyright__text">
                    <p>Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | Develop by <a href="https://avietechy.w3spaces.com/" target="_blank">AvieTechy</a></p>
                </div>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

templates/snippets/header.html
{% load static %}
 <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__close">+</div>
        <ul class="offcanvas__widget">
            <li><span class="icon_search search-switch"></span></li>
            <li><a href="#"><span class="icon_heart_alt"></span>
                <div class="tip">0</div>
            </a></li>
            <li><a href="{% url 'shop:my_cart' %}"><span class="icon_bag_alt"></span>
                <div class="tip">{{cart_cnt}}</div>
            </a></li>
        </ul>
        <div class="offcanvas__logo">
            <a href=""><img src="{% static 'Ecomex1/img/logo.jpg'%}" alt=""></a>
        </div>
        <div class="offcanvas__auth">
            <div class="shop__sidebar">
                        <div class="sidebar__categories">
                            <div class="categories__accordion">
                                <div class="accordion" id="accordionExample">
                                    {%if request.user.is_staff == True %}
                                    <div class="card">
                                        <div class="card-heading">
                                            <a href="{% url 'revenue:revenue_view' %}">Revenue</a>
                                        </div>
                                    </div>
                                    <div class="card">
                                        <div class="card-heading">
                                            <a href="./shop.html">Orders</a>
                                        </div>
                                    </div>
                                    <div class="card">
                                        <div class="card-heading">
                                            <a data-toggle="collapse" data-target="#collapseTwo">Products</a>
                                        </div>
                                        <div id="collapseTwo" class="collapse" data-parent="#accordionExample">
                                            <div class="card-body">
                                                <ul>
                                                    <li><a class="dropdown-item" href="/products/items">Items</a></li>
                                                    <li><a class="dropdown-item" href="{% url 'product:collections' %}">Collections</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card">
                                        <div class="card-heading">
                                            <a href="./shop.html">Customers</a>
                                        </div>
                                    </div>
                                    {% else %}
                                        <div class="card">
                                        <div class="card-heading">
                                            <a href="/">Home</a>
                                        </div>
                                    </div>
                                    <div class="card">
                                        <div class="card-heading">
                                            <a href="{% url 'shop:shop_view' %}">Shop</a>
                                        </div>
                                    </div>
                                    <div class="card">
                                        <div class="card-heading">
                                            <a data-toggle="collapse" data-target="#collapseTwo1">Women’s</a>
                                        </div>
                                        <div id="collapseTwo1" class="collapse" data-parent="#accordionExample">
                                            <div class="card-body">
                                                <ul>
                                                    <li><a class="dropdown-item" href="./error404">Top</a></li>
                                                    <li><a class="dropdown-item" href="./error404">Bottom</a></li>
                                                    <li><a class="dropdown-item" href="./error404">Outdoor</a></li>
                                                    <li><a class="dropdown-item" href="./error404">Accessories</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card">
                                        <div class="card-heading">
                                            <a data-toggle="collapse" data-target="#collapseTwo2">Men’s</a>
                                        </div>
                                        <div id="collapseTwo2" class="collapse" data-parent="#accordionExample">
                                            <div class="card-body">
                                                <ul>
                                                    <li><a class="dropdown-item" href="./error404">Top</a></li>
                                                    <li><a class="dropdown-item" href="./error404">Bottom</a></li>
                                                    <li><a class="dropdown-item" href="./error404">Outdoor</a></li>
                                                    <li><a class="dropdown-item" href="./error404">Accessories</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card">
                                        <div class="card-heading">
                                            <a href="{% url 'product:collections' %}">Collections</a>
                                        </div>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
            </div>
        </div>
        <div class="offcanvas__auth">
             {% if request.user.is_authenticated %}
                <a href="/logout">Logout</a>
                {% if request.user.is_staff == True %}
                <a href="/manage">Manage</a>
                {% endif %}
            {% else %}
            <a href="/login">Login</a>
            <a href="/register">Register</a>
            {% endif %}
        </div>
    </div>
    <header class="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-5 col-lg-7">
                    <nav class="header__menu">
                        <ul>
                            {%if request.user.is_staff == True %}
                                {% if status == "revenue" %}
                                    <li class="active"><a href="{% url 'revenue:revenue_view' %}">Revenue</a></li>
                                {% else %}
                                    <li><a href="{% url 'revenue:revenue_view' %}">Revenue</a>
                                {% endif %}

                                {% if status == "orders" %}
                                    <li class="active"><a href="{% url 'orders:orders_view' %}">Orders</a></li>
                                {% else %}
                                    <li><a href="{% url 'orders:orders_view' %}">Orders</a>
                                {% endif %}

                                {% if status == "products" %}
                                <li class="active"><a href="#">Products</a>
                                {% else %}
                                    <li><a href="#">Products</a>
                                {% endif %}
                                    <ul class="dropdown">
                                            <li><a class="dropdown-item" style="color: #F2D1D1" href="/products/items">Items</a></li>
                                            <li><a class="dropdown-item" style="color: #F2D1D1" href="{% url 'product:collections' %}">Collections</a></li>
                                    </ul>
                                </li>
                               {% if status == "customers" %}
                                <li class="active"><a href="#">customers</a>
                                {% else %}
                                    <li><a href="#">customers</a>
                                {% endif %}
                            {% else %}
                                {% if status == "home" %}
                                <li class="active"><a href="/">Home</a></li>
                                {% else %}
                                <li><a href="/">Home</a></li>
                                {% endif %}

                                {% if status == "shop" %}
                                <li class="active"><a href="{% url 'shop:shop_view' %}">Shop</a></li>
                                {% else %}
                                <li><a href="{% url 'shop:shop_view' %}">Shop</a></li>
                                {% endif %}
                            <li><a href="#">Women’s</a>
                                <ul class="dropdown">
                                        <li><a class="dropdown-item" style="color: #F2D1D1" href="./error404">Top</a></li>
                                        <li><a class="dropdown-item" style="color: #F2D1D1" href="./error404">Bottom</a></li>
                                        <li><a class="dropdown-item" style="color: #F2D1D1" href="./error404">Outdoor</a></li>
                                        <li><a class="dropdown-item" style="color: #F2D1D1" href="./error404">Accessories</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Men’s</a>
                                <ul class="dropdown">
                                        <li><a class="dropdown-item1" style="color: #C6DCE4" href="./error404">Top</a></li>
                                        <li><a class="dropdown-item1" style="color: #C6DCE4" href="./error404">Bottom</a></li>
                                        <li><a class="dropdown-item1" style="color: #C6DCE4" href="./error404">Outdoor</a></li>
                                        <li><a class="dropdown-item1" style="color: #C6DCE4" href="./error404">Accessories</a></li>
                                </ul>
                            </li>
                            {% if status == "collection" %}
                                <li class="active"><a href="{% url 'product:collections' %}">Collections</a></li>
                                {% else %}
                                <li><a href="{% url 'product:collections' %}">Collections</a></li>
                                {% endif %}

                            {% endif %}
                        </ul>
                    </nav>
                </div>
                <div class="col-xl-4 col-lg-2">
                    <div class="header__logo">
                        <a href="/"><img src="{% static 'Ecomex1/img/logo.jpg'%}" alt="" style='width: 150px; height: 100%; margin-bottom: -20px; margin-top: -15px; object-fit: contain;'></a>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="header__right">
                        <div class="header__right__auth">
                            {% if request.user.is_authenticated %}
                                <a href="/logout">Logout</a>
                                {% if request.user.is_staff == True %}
                                    <a href="/manage">Manage</a>
                                {% endif %}
                            {% else %}
                            <a href="/login">Login</a>
                            <a href="/register">Register</a>
                            {% endif %}
                        </div>

                        <ul class="header__right__widget">
                            <li><span class="icon_search search-switch"></span></li>
                            <li><a href="#"><span class="icon_heart_alt"></span>
                                <div class="tip">0</div>
                            </a></li>
                            {%if request.user.is_staff == False %}
                            <li><a href="{% url 'shop:my_cart' %}"><span class="icon_bag_alt"></span>
                                <div class="tip">{{cart_cnt}}</div>
                            </a></li>
                            {% else %}
                            <li><a href="#"><span class="icon_bag_alt"></span>
                                <div class="tip">0</div>
                            </a></li>
                            {% endif %}
                        </ul>

                    </div>
                </div>
            </div>
            <div class="canvas__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->