Ecomex/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.conf.urls import include

from account.views import (
    register_view, login_view, logout_view, manage_view
)
from EcomexApp.views import (
    index, error404,
)

urlpatterns = [
	path('admin/', admin.site.urls),
    path('register/', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('manage/', manage_view, name="manage"),

    path('', index, name="index"),
    path('error404/', error404, name="error404"),

    #snippets
    path('products/', include('product.urls', namespace='product')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('revenue/', include('revenue.urls', namespace='revenue')),

] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path

from shop.views import (
    shop_view, detail, add_order, my_cart, update_cart, checkout,
    send_order
    )

app_name = 'shop'

urlpatterns = [
    #shop
	path('', shop_view, name="shop_view"),
	path('detail/<str:pro_id>', detail, name="detail"),
	path('add_order', add_order, name="add_order"),
	path('my_cart', my_cart, name="my_cart"),
	path('update_cart', update_cart, name="update_cart"),
    path('checkout', checkout, name="checkout"),
    path('send_order', send_order, name="send_order"),
]

shop/models.py
from django.db import models
from datetime import datetime

now = datetime.now()
date_time = now.strftime("%m/%d/%Y, %H:%M:%S")


from account.models import Account
from product.models import Products


class Cart(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    items = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    color = models.CharField(default="", max_length=255)
    size = models.CharField(default="", max_length=255)
    status = models.BooleanField(default=True)
    objects = models.Manager()

class Info_Order(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=255)
    optinal = models.CharField(max_length=255, default="-")
    city = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    postcode = models.CharField(max_length=255)
    objects = models.Manager()

class ListOrders(models.Model):
    id = models.AutoField(primary_key=True)
    info = models.ForeignKey(Info_Order, on_delete=models.CASCADE)
    note = models.CharField(max_length=255, default="-")
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    date = models.CharField(max_length=255, default=date_time)
    subtotal = models.CharField(max_length=255)
    status_order = models.CharField(max_length=255, default="pending")
    objects = models.Manager()

shop/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

# Create your views here.
from product.models import Products, Product_color, Product_size, Product_image, Collections
from django.template.defaulttags import register

from shop.models import Cart, ListOrders, Info_Order


@register.filter(name='get_item')
def get_item(dictionary, key):
    return dictionary.get(key)


def vertify_user(request):
    if (request.user.is_authenticated):
        return "ok"
    else:
        return "error"


def shop_view(request):
    status = "shop"
    cart_cnt = 0
    if vertify_user(request) == "ok":
        cart_cnt = Cart.objects.filter(user=request.user, status=True).count()
    context, colors, sizes, images = {}, {}, {}, {}
    products = []
    if (Products.objects.all().count() != 0):
        products = Products.objects.all()
        for product in products:
            colors[product] = Product_color.objects.filter(product_id=product)
            sizes[product] = Product_size.objects.filter(product_id=product)
            for i in Product_image.objects.filter(product_id=product):
                print(i.key)
            print(Product_image.objects.filter(product_id=product).count())
            image = Product_image.objects.get(product_id=product, key=True)

            images[product] = image.product_image.url
    context = {'status': status, 'colors': colors, 'sizes': sizes, 'images': images, 'products': products,
               'cart_cnt': cart_cnt}
    print(cart_cnt)
    return render(request, 'shop.html', context)


def detail(request, pro_id):
    status = "shop"
    cart_cnt = 0
    if vertify_user(request) == "ok":
        cart_cnt = Cart.objects.filter(user=request.user, status=True).count()

    ID = pro_id
    thumbs = {}
    urls = {}
    rate_rel = {}
    orate_rel = {}
    product = Products.objects.get(id=pro_id)
    images = Product_image.objects.filter(product_id=product)
    colors = Product_color.objects.filter(product_id=product)
    sizes = Product_size.objects.filter(product_id=product)
    related = Products.objects.filter(collection=product.collection)
    for rel in related:
        image = Product_image.objects.get(product_id=rel, key=True)
        thumbs[rel] = image
        urls[rel] = image.product_image.url
        rate_rel[rel] = [1] * rel.rate
        orate_rel[rel] = [1] * (5 - rel.rate)
    rate = [1] * product.rate
    orate = [1] * (5 - product.rate)

    print(related)
    print("rel")
    context = {'status': status, 'ID': ID, 'product': product, 'images': images, 'rate': rate,
               'orate': orate, 'colors': colors, 'sizes': sizes, 'related': related, 'thumbs': thumbs,
               'urls': urls, 'rate_rel': rate_rel, 'orate_rel': orate_rel, 'cart_cnt': cart_cnt}

    return render(request, "detail.html", context)


def add_order(request):
    status = "shop"
    cart_cnt = 0
    if vertify_user(request) == "ok":
        pro_id = request.POST.get('pro_id')
        qty = request.POST.get('qty')
        color_choice = request.POST.get('color_choice')
        size = request.POST.get('size')

        product = Products.objects.get(id=pro_id)
        if Cart.objects.filter(user=request.user, items=product, color=color_choice, size=size,
                               status=True).count() == 0:
            cart = Cart(user=request.user, items=product, color=color_choice, size=size, status=True)
            cart.save()
        cart = Cart.objects.get(user=request.user, items=product, color=color_choice, size=size, status=True)
        cart.quantity = qty
        cart.save()
        cart_cnt = Cart.objects.filter(user=request.user, status=True).count()
        context = {'status': status, 'cart_cnt': cart_cnt}
        messages.success(request, 'Added in your cart!')
        return redirect("shop:detail", pro_id)
    else:
        messages.warning(request, 'Please Login First!')
        return redirect("login")


def my_cart(request):
    status = "shop"
    cart_cnt = 0
    if vertify_user(request) == "ok":
        orders = []
        thumbs = {}
        total = {}
        subtotal = 0

        orders = Cart.objects.filter(user=request.user, status=True)
        cart_pend = Cart.objects.filter(user=request.user, status=False)
        pends = []
        cnt = {}
        para = 0
        for cart_p in cart_pend:
            if ListOrders.objects.filter(cart=cart_p).count() == 1:
                ord = ListOrders.objects.get(cart=cart_p)
                pends.append(ord)
                para += 1
                cnt[ord] = para

        for order in orders:
            thumb = Product_image.objects.get(product_id=order.items, key=True)
            thumbs[order] = thumb.product_image.url
            total[order] = order.items.price * order.quantity
            subtotal += total[order]

        cart_cnt = Cart.objects.filter(user=request.user, status=True).count()
        context = {'cart_cnt': cart_cnt, 'status': status, 'orders': orders, 'thumbs': thumbs,
                   'total': total, 'subtotal': subtotal, 'pends': pends, 'cnt':cnt}
        return render(request, "my_cart.html", context)
    else:
        messages.warning(request, 'Please Login First!')
        return redirect("login")


def update_cart(request):
    status = "shop"
    cart_cnt = 0
    if vertify_user(request) == "ok":
        print("vao")
        print(request.POST)
        if request.POST:
            try:
                items = Cart.objects.filter(user=request.user, status=True)
                for item in items:
                    qty = 0
                    if str(item.id) in request.POST:
                        qty = request.POST[str(item.id)]
                    print(qty)
                    if qty == 0 or qty == '0':
                        Cart.objects.get(id=item.id).delete()
                    else:
                        item.quantity = qty
                        item.save()
                messages.success(request, 'Updated Your Cart!')

                return redirect("shop:my_cart")
            except:
                messages.error(request, 'There was an error while updating your cart. Please try again!')
                return redirect("shop:my_cart")

    else:
        messages.warning(request, 'Please Login First!')
        return redirect("login", {'cart_cnt': cart_cnt})


def checkout(request):
    status = "shop"
    cart_cnt = 0
    total = {}
    subtotal = 0

    if vertify_user(request) == "ok":
        cart_cnt = Cart.objects.filter(user=request.user, status=True).count()

        if cart_cnt == 0:

            messages.info(request, "Nothing is in your cart at the moment. Pick some from this list!")
            return redirect("shop:shop_view")
        else:
            orders = Cart.objects.filter(user=request.user, status=True)
            for order in orders:
                total[order] = order.items.price * order.quantity
                subtotal += total[order]
            context = {'orders': orders, 'total': total, 'subtotal': subtotal, 'cart_cnt': cart_cnt,
                       'status': status}
            return render(request, 'checkout.html', context)

    else:
        messages.warning(request, 'Please Login First!')
        return redirect("login", {'cart_cnt': cart_cnt})


def send_order(request):
    status = "shop"
    cart_cnt = 0
    if vertify_user(request) == "ok":
        if request.POST:
            # require
            name = request.POST['cus_name']
            email = request.user.email
            phone = request.POST['phone']
            city = request.POST['city']
            country = request.POST['country']
            street = request.POST['street']
            postcode = request.POST['postcode']

            optinal = "-"
            note = "-"
            if request.POST['optinal'] != '':
                optinal = request.POST.get('optinal')
            if request.POST['note'] != '':
                note = request.POST.get('note')

            print(name, email, phone, postcode, city, country, street, optinal, note)
            try:
                carts = Cart.objects.filter(user=request.user, status=True)
                for cart in carts:
                    subtotal = cart.items.price * cart.quantity
                    cart.status = False
                    if Info_Order.objects.filter(user=request.user, name=name, email=email, phone=phone,
                                                 optinal=optinal, city=city, country=country, street=street,
                                                 postcode=postcode).count() == 0:
                        print("vao")
                        info = Info_Order(user=request.user, name=name, email=email, phone=phone, optinal=optinal,
                                          city=city, country=country, street=street, postcode=postcode)
                        info.save()

                    info = Info_Order.objects.get(user=request.user, name=name, email=email, phone=phone,
                                                  optinal=optinal, city=city,
                                                  country=country, street=street, postcode=postcode)
                    print(info)
                    print("success info")
                    list_orders = ListOrders(info=info, note=note, cart=cart, subtotal=subtotal)
                    list_orders.save()
                    print(list_orders)
                    print("success list_orders")
                    # info.save()
                    cart.save()
                messages.success(request, 'Your order is pending!')
                return redirect("shop:my_cart")
            except:
                messages.error(request, 'Failed in Sending your checkout!')
                return redirect("shop:checkout")

    else:
        messages.warning(request, 'Please Login First!')
        return redirect("login", {'cart_cnt': cart_cnt})

shop/templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

{% endblock css %}

{% block content %}
<section class="checkout spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h6 class="coupon__link"><span class="icon_tag_alt"></span> <a href="#">Have a coupon?</a> Click
                here to enter your code.</h6>
            </div>
            <div class="col-lg-12">
                {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger alert-dismissible fade show" style="text-align: center;" role="alert">
                      <strong>{{message.tags}}:</strong> {{message}}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    {% else %}
                        <div class="alert alert-{{message.tags}} alert-dismissible fade show" style="text-align: center;" role="alert">
                      <strong>{{message.tags}}:</strong> {{message}}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            </div>
        </div>
        <form action="{% url 'shop:send_order' %}" class="checkout__form" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-8">
                    <h5>Billing detail</h5>
                    <div class="row">
                        <div class="col-lg-12 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <p>What can I call you? <span>*</span></p>
                                <input type="text" name="cus_name" required>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <p>Phone <span>*</span></p>
                                <input type="text" name="phone" required>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <p>Email <span>*</span></p>
                                <input type="email" disabled value="{{request.user.email}}" name="email">
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="checkout__form__input">
                                <p>Address <span>*</span></p>
                                <input type="text" placeholder="Street Address" name="street" required>
                                <input type="text" placeholder="Apartment. suite, unite ect ( optinal )" name="optinal">
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="checkout__form__input">
                                <p>Town/City <span>*</span></p>
                                <input type="text" name="city" required>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="checkout__form__input">
                                <p>Country/State <span>*</span></p>
                                <input type="text" name="country" required>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="checkout__form__input">
                                <p>Postcode/Zip <span>*</span></p>
                                <input type="text" name="postcode" required>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="checkout__form__input">
                                <p>Oder notes</p>
                                <input type="text" name="note"
                                placeholder="Note about your order, e.g, special noe for delivery">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="checkout__order">
                        <h5>Your order</h5>
                        <div class="checkout__order__product">
                            <ul>
                                <li>
                                    <span class="top__text">Product</span>
                                    <span class="top__text__right">Total</span>
                                </li>
                                {% for order in orders %}
                                <li>01. {{order.items.name}} <span>$ {{total|get_item:order}}</span></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="checkout__order__total">
                            <ul>
                                <li>Subtotal <span>$ {{subtotal}}</span></li>
                                <li>Total <span>$ {{subtotal}}</span></li>
                            </ul>
                        </div>
                        <div class="checkout__order__widget">
                            <label for="check-payment">
                                Cash payment
                                <input type="checkbox" id="check-payment" checked>
                                <span class="checkmark" ></span>
                            </label>
                            <label for="paypal">
                                PayPal <small>is NOT available now!</small>
                                <input type="checkbox" id="paypal" disabled>
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <input type="text" hidden name="subtotal" value="{{subtotal}}">
                        <button type="submit" class="site-btn">Confirm order</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
{% endblock content %}

{% block js %}
{% endblock js %}

shop/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
{% endblock css %}

{% block content %}
<section class="product-details spad">
        <div class="container">
            <div class="row">
                <div class="col-12">
                   {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger alert-dismissible fade show" style="text-align: center;" role="alert">
                      <strong>{{message.tags}}:</strong> {{message}}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    {% else %}
                        <div class="alert alert-{{message.tags}} alert-dismissible fade show" style="text-align: center;" role="alert">
                      <strong>{{message.tags}}:</strong> {{message}}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
                </div>
                <div class="col-lg-6">
                    <div class="product__details__pic">
                        <div class="product__details__pic__left product__thumb nice-scroll">
                            {% for img in images %}
                            <a class="pt active" href="#product-{{img.id}}">
                                <img src="{{img.product_image.url}}" alt="">
                            </a>
                            {% endfor %}
                        </div>
                        <div class="product__details__slider__content">
                            <div class="product__details__pic__slider owl-carousel">
                                {% for img in images %}
                                <img data-hash="product-{{img.id}}" class="product__big__img" src="{{img.product_image.url}}" alt="">
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">

                    <div class="product__details__text">
                        <h3>{{product.name}} <span>Brand: {{product.brand}}</span></h3>
                        <div class="rating">
                            {% for star in rate %}
                            <i class="fa fa-star"></i>
                            {% endfor %}
                            {% for star in orate %}
                            <i class="icon_star_alt"></i>
                            {% endfor %}
                            {% if product.rate == 0 %}
                            <span>( No review yet! )</span>
                            {%else%}
                            <span>( 138 reviews )</span>
                            {% endif %}
                        </div>
                        <div class="product__details__price">$ {{product.price}}</div>
                        <p>{{product.detail}}</p>
                        <form action="{% url 'shop:add_order' %}" method="POST">
                            {% csrf_token %}
                            <input type="text" hidden name="pro_id" value="{{ID}}">
                            <div class="product__details__button">
                                <div class="quantity">
                                    <span>Quantity:</span>
                                    <div class="pro-qty">
                                        <input type="text" name="qty" value="0" id="qty">
                                    </div>
                                </div>
                                <button type="submit" class="cart-btn" style="border"><span class="icon_bag_alt"></span> Add to cart</button>
                                <ul>
                                    <li><a href="#"><span class="icon_heart_alt"></span></a></li>
                                    <li><a href="#"><span class="icon_adjust-horiz"></span></a></li>
                                </ul>
                            </div>
                            <div class="product__details__widget">
                                <ul>
                                    <li>
                                        <span>Availability:</span>
                                        <div class="stock__checkbox">
                                            {% if product.Availability == True %}
                                            In Stock <i class="fa fa-cart-plus"></i>
                                            {% else %}
                                            Out of Stock <i class="icon_minus_alt"></i>
                                            {% endif %}
                                        </div>
                                    </li>
                                    <li>
                                        <span>Available color:</span>
                                        <div class="color__checkbox">
                                            {% for color in colors %}
                                            <label for="{{color.name}}">
                                                <input type="radio" name="color_choice" value="{{color.name}}" id="{{color.name}}">
                                                <span class="checkmark {{color.name}}-bg"></span>
                                            </label>
                                            {% endfor %}
                                        </div>
                                    </li>
                                    <li>
                                        <span>Available size:</span>
                                        <div class="size__btn">
                                            {% for size in sizes %}
                                            <label for="{{size.name_size}}-btn" class="badge badge-light" style="font-weight: bold;">
                                                <input type="radio" name="size" value="{{size.name_size}}" id="{{size.name_size}}-btn">
                                                {{size.name_size}}
                                            </label>
                                            {% endfor %}
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="product__details__tab">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">Description</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tabs-1" role="tabpanel">
                                <h6>Description</h6>
                                <p>{{product.Description}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="related__title">
                        <h5>RELATED PRODUCTS</h5>
                    </div>
                </div>
                {% for rel in related %}
                {% if rel != product %}
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" data-setbg="{{urls|get_item:rel}}">
                            <div class="label new">New</div>
                            <ul class="product__hover">
                                <li><a href="{{urls|get_item:rel}}" class="image-popup"><span class="arrow_expand"></span></a></li>
                                <li><a href="#"><span class="icon_heart_alt"></span></a></li>
                                <li><a href="#"><span class="icon_bag_alt"></span></a></li>
                            </ul>
                        </div>
                        <div class="product__item__text">
                            <h6><a href="#">{{rel.name}}</a></h6>
                            <div class="rating">
                                {% for star in rate_rel|get_item:rel %}
                                <i class="fa fa-star"></i>
                                {% endfor %}
                                {% for star in orate_rel|get_item:rel %}
                                <i class="icon_star_alt"></i>
                                {% endfor %}
                            </div>
                            <div class="product__price">$ {{rel.price}}</div>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </section>


{% endblock content %}

{% block js %}
<script>

</script>
{% endblock js %}